### ISSUE TITLE
coq-high-school-geometry packages

### ISSUE THREAD

**Issue by CohenCyril** [coq/opam-coq-archive#1299]
_Originally posted by @herbelin in https://github.com/coq/opam-coq-archive/issues/1298#issuecomment-644406994_
> Hi @CohenCyril, thanks for your message. The sources of coq-high-school-geometry have moved on https://github.com/coq-contribs/high-school-geometry for some time now (though, unfortunately, I renounced to adapt high-school-geometry to Coq 8.7: the `IZR` change in the representation of real constants was too difficult to manage).

**Comment by CohenCyril** [comment]
@herbelin indeed, it seems that https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-high-school-geometry/coq-high-school-geometry.8.6.0/opam (which you are a maintainer of) makes no reference to github. However @thery's package https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-high-school-geometry/coq-high-school-geometry.1.0.0/opam#L3 makes reference to gforge.inria.fr as its homepage.

BTW I find it disturbing that this package is maintained by two different persons, with two different source repositories (and homepages) and with a difference version convention... Should we do something about it?

**Comment by thery** [comment]
@CohenCyril @herbelin 
If I remember correctly I set up my githup repository because Pierre Marie (Madiot) wanted a link to one of the 100 theorems list for Coq (I think it is Morley but I am not sure).. So my version my different maybe differ from the standard one because it includes an extra file. 
Frédérique (Guilhot) was a nice person, so I think it would be nice to keep on supporting the library. So I did the port to 8.11 (affective port :smile:) it is commit 34e57ecc464c290fb08e30626ab284fa6d2e41f1.
Now we have to decide where to move the gforge stuff so I can shut down my repository.

**Comment by palmskog** [comment]
@thery I applaud any Coq porting efforts (affective or otherwise), but now we have two incomparable repositories with different Coq compatibility:
- https://github.com/thery/HighSchoolGeometry
- https://github.com/coq-contribs/high-school-geometry

Would you consider maintaining your repository as the official one in coq-community? In that case, we can mark the other repository as read-only. As for previous releases on gforge, we can put those in a "legacy" GitHub release, like Enrico did for MathComp: https://github.com/math-comp/math-comp/releases/tag/archive

What do you think?

**Comment by herbelin** [comment]
I applaud too!

I think https://github.com/coq-contribs/high-school-geometry can be dropped. I was just maintaining it to the Coq version, so the version which works with 8.11 should be kept instead (in any suitable repository, e.g. coq-community).

**Comment by thery** [comment]
> @thery I applaud any Coq porting efforts (affective or otherwise), but now we have two incomparable repositories with different Coq compatibility:
> 
>     * https://github.com/thery/HighSchoolGeometry
> 
>     * https://github.com/coq-contribs/high-school-geometry
> 
> 
> Would you consider maintaining your repository as the official one in coq-community? In that case, we can mark the other repository as read-only. As for previous releases on gforge, we can put those in a "legacy" GitHub release in the coq-community repo, like Enrico did for MathComp: https://github.com/math-comp/math-comp/releases/tag/archive
> 
> What do you think?

@palmskog  fine with me

**Comment by thery** [comment]
> I think https://github.com/coq-contribs/high-school-geometry can be dropped.

@herbelin  ok

**Comment by palmskog** [comment]
Since #1325 was merged, I think we can close this (packages were unified an have no references to gforge).
