### ISSUE TITLE
Flocq bug reports

### ISSUE THREAD

**Issue by liyishuai** [coq/opam-coq-archive#1418]
https://github.com/coq/opam-coq-archive/blob/c4015216678480f1ed14831aa32fcdc6424a1ad1/released/packages/coq-flocq/coq-flocq.3.3.1/opam#L5
Can the general public open issues there?

**Comment by silene** [comment]
Sure. The only thing you are not allowed to do is to create projects (be they new or fork of existing ones).

**Comment by liyishuai** [comment]
Outsiders looking to get an account: https://gitlab.inria.fr/siteadmin/doc/-/wikis/home#gitlab-accounts

**Comment by Zimmi48** [comment]
FTR it used to be the case that people outside Inria could create an external account and report issues, without any a priori interaction with an Inria employee. But, as described on this wiki page, this isn't true anymore. Now, external accounts have to be sponsored by an Inria employee, have to be renewed every year and the sponsorship has to be transferred to some other employee if the initial sponsor is leaving Inria. This is an incredible amount of barriers to put to someone just wanting to contribute by reporting an issue*. I'm personally outraged by this choice of Inria of making their GitLab such a closed platform.

*And this is even worse of course to open a pull request since you basically have to give them write-access to your repo so that they can open one, or you have to manually manage the pull request through an issue and a fork on GitHub.

**Comment by silene** [comment]
@liyishuai You created an account and submitted a bug report two hours ago. Were you sponsored by an Inria employee?

**Comment by palmskog** [comment]
@silene he got help from @Zimmi48, see [this Zulip topic](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs.20.26.20plugin.20devs/topic/Flocq.20bug.20report).

**Comment by Zimmi48** [comment]
I also had to sponsor @MSoegtropIMC similarly even though he previously held an external account that he had created by himself.

**Comment by silene** [comment]
I am flabbergasted by this (recent?) change of policy. While I could understand the need to prevent external people from hosting their data on Inria servers, preventing them from reporting bugs does not make any sense to me.

**Comment by Zimmi48** [comment]
I have no idea how long this has been in place. I discovered it when Michael requested my help to get an account back in July.

**Comment by ybertot** [comment]
It may be because a false bug report may be used to propagate spam information.  I experience the same kind of problem with a blog I tried to write, which is periodically invaded by spam message trying to advertise any kind of bizarre products.

**Comment by ejgallego** [comment]
@silene unfortunately Inria hosting policy is incompatible will some of the tooling goals that have been expressed a few times; it is possible that in the medium / long term projects not hosted in an "open" [to users] platform have to be dropped from Coq's CI.

In particular we'd like bots to be able to automatically submit and merge PRs.

**Comment by Zimmi48** [comment]
> It may be because a false bug report may be used to propagate spam information. I experience the same kind of problem with a blog I tried to write, which is periodically invaded by spam message trying to advertise any kind of bizarre products.

I don't buy this argument. Spam detectors can be pretty effective, as I can see on Discourse (where literally *every* spam attempt is automatically flagged as such and staged in a moderator review queue), and I doubt that GitLab doesn't ship with such a detector by default.

**Comment by ejgallego** [comment]
Well spam is sadly a trouble, and sometimes quite tricky. For example I have been impacted by the most stupid mailman subscription spam [which is really a DOS as it only annoys people] which actually is not possible to prevent.

Now, mails from my domain are moved into the spam folder by google :S
