### ISSUE TITLE
Colons in package names

### ISSUE THREAD

**Issue by AltGr** [coq/opam-coq-archive#16]
I am very sorry about this since I took part in [advising it](http://lists.ocaml.org/pipermail/opam-devel/2014-October/000772.html) ; but it turns out this is a terrible idea for Windows support, as package names need to appear in file names, and Windows really doesn't like colons in file names.

See https://github.com/ocaml/opam/issues/2320 for the original discussion on colons, package names and Windows.

**Comment by clarus** [comment]
Thanks for reporting this bug! This is indeed critical.

Should we change to a `-`? (probably the safest option) Or to another character such as `@`?

This bug stresses that we do not have a bench or someone verifying that OPAM works for Coq under Windows (neither under Mac OS X by the way). I will find a way to test these platforms this week.

**Comment by clarus** [comment]
Since we will probably need to change the names of the packages, should we take a convention on the package names with respect to their installation folder?

More precisely, if a package is in the namespace `coq`:`a`:...:`z`, should we enforce all the files installed in `user-contribs` to be in the folder `user-contribs/a/.../z`? In particular, this requires to keep a special character for the namespaces (such as `@`) and allow package names with lower/upper cases.

**Comment by dbuenzli** [comment]
So we were planning to raise this with @dra27 a few hours ago as he has been making great progress on opam for windows but @AltGr beat us to report. Just calling in @dra27 so that he can also follow the discussion.

Regarding the issue at hand I think that we are maybe missing a mechanism in opam so that opam repositories can be limited to certain switches. @clarus Do you think it actually makes sense to have switches with both coq packages and ocaml ones ? (Maybe because of extraction ?)

I mean I don't see why coq users should be bothered with writing a `coq:` prefix for installing their packages. I also find the idea of encoding hierarchy in package names a bit suspicious. 

Other than that yes `-` seems to be a safe choice.

**Comment by clarus** [comment]
Thanks for your comment.

> Do you think it actually makes sense to have switches with both coq packages and ocaml ones ? (Maybe because of extraction ?)

Yes, this is because of the extraction and OCaml plugins for Coq which may have OCaml dependencies. Coq and CoqIDE also have some dependencies. But maybe we overestimate the need of OCaml dependencies.

> I also find the idea of encoding hierarchy in package names a bit suspicious.

Ok. I agree that these ideas of namespaces and hierarchies may not be necessary.

**Comment by clarus** [comment]
Since this is a breaking change, I propose to take a decision over the new naming conventions on the next [CoqWG](https://coq.inria.fr/cocorico/CoqDevelopment/NextCoqWG).

**Comment by dra27** [comment]
Is it breaking to change coq:shell in opam-repository to coq-shell in the meantime? I'm hoping to be able to advertise an alpha release of opam within the next week or so, and it would be nice to have the facility to add the official opam-repository as a git remote which at the moment the colon in this and one other (non-Coq) package prevents.
Slightly less gory details for Windows naming conventions are available [here](https://msdn.microsoft.com/en-gb/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions) - I wouldn't worry about the "con, aux, prn", etc. device-files; just the reserved characters.

**Comment by clarus** [comment]
I think this is fine, but we would need a confirmation from @gares.

**Comment by haochenx** [comment]
I'm a coq user on Windows (for the half time, and on Mac OS X for the other), and due to this problem i could not use OPAM for installing coq (I'd rather like to do so if I could.) I'm currently using the Windows binary offered on the Coq website, and I'll be willing to help test coq's OPAM package on windows in the future (just tell me what to do and where to submit test reports)

**Comment by dra27** [comment]
@haochenx - marvellous, thanks! The best thing at the moment would be to subscribe to either or both of [opam-devel](http://lists.ocaml.org/listinfo/opam-devel) or [wg-windows](http://lists.ocaml.org/listinfo/wg-windows) (they're both low-traffic email lists).
I'm at present working on polishing a few aspects of packaging and hoping to make an alpha release of native Windows support for OPAM in the next week or so (which will be announced on both those mailing lists).

**Comment by clarus** [comment]
Thanks @haochenx! You can submit issues and reports on this bug tracker.

**Comment by clarus** [comment]
I just added the [Pull request 25](https://github.com/coq/opam-coq-archive/pull/25) to solve this issue.

**Comment by clarus** [comment]
I propose to accept this pull request on Monday, 1:00 pm UTC. By this time, we must update our tools.

**Comment by haochenx** [comment]
Sorry for my inactivity and thanks for all you guy's work and suggestions. I'll for sure subscribe those mail lists and check the pull request.

**Comment by dra27** [comment]
Note also that https://github.com/ocaml/opam-repository/pull/5090 was merged on Thursday so `coq:shell` in the main OPAM repository is now `coq-shell`

**Comment by clarus** [comment]
Thanks for the merge! Due to a request from @herbelin, we will actually agree on this pull-request for the [next working group](https://coq.inria.fr/cocorico/CoqDevelopment/NextCoqWG) of Coq, on November the 25th.
