### ISSUE TITLE
coq-coqide.dev broken

### ISSUE THREAD

**Issue by eponier** [coq/opam-coq-archive#164]
The problem seems commit 419e7cac23d7b8ac97d46a6c0d3228d591273d2b that removed target `coqide-binaries`.

The error obtained when compiling is
`no rule to make target coqide-binaries`

**Comment by letouzey** [comment]
See bug [5667](http://coq.inria.fr/bug/5667) :

I've just restored a coqide-binaries target (commit 9d8ac8500 in master) that builds `bin/coqide` and `bin/coqide.byte`. Feel free to backport to 8.7 if needed.
That said, I think it's better to adapt the opam build rule, in order for it to build first the target `coqide-opt`, then `coqide-byte`, in order to avoid mixing byte and native OCaml compilations (cf. the potential race conditions for `.cmi`).
Btw, do we really need `coqide.byte` in this opam package coq-coqide ? If `coqide.byte` has indeed some use, I'd advocate putting it in a separate package coq-coqide-debug or something similar.

**Comment by ejgallego** [comment]
fixed
