### ISSUE TITLE
Coq beta in released

### ISSUE THREAD

**Issue by clarus** [coq/opam-coq-archive#17]
Should we keep Coq `8.5~beta2` in the `released` directory?

**Comment by clarus** [comment]
This problem was cited by @Matafou, @jhjourdan and @arthuraa.

**Comment by clarus** [comment]
I propose to move the `8.5~beta2` to the `core-dev` repository, if no one complain by next week.

**Comment by Matafou** [comment]
Fine with me.  IMHO since beta3 seems on the go you should ask Maxime before doing anything, and do the same with beta3?

**Comment by clarus** [comment]
OK, I just sent him an email.

**Comment by gares** [comment]
In the "big plan" documented in the not-yet-released page https://coq.inria.fr/opam/www/policy.html 8.5~beta2 should be in released, but not in the stable-8.4 nor stable-8.5 "views".

**Comment by Matafou** [comment]
That sounds reasonable to me too. How far from this big plan are we actually?

**Comment by gares** [comment]
I hope we will make these pages public with beta3

**Comment by clarus** [comment]
To this policy, I would just add that the `released` repository is the one for regular users, and the `stable-$VERSION` the one for people who seek stability. The rationale is that most programming language communities (OCaml, Java, JavaScript, Ruby, Python and R for examples) tend to prefer the `released` approach by default. Since we are building a practical tool, we should be inspired by the experience acquired by other communities. I think OCamlPro got it right with OPAM for OCaml, we should continue in this way.

As a minor point, I would also forbid updates with breaking changes in the stable repositories.

**Comment by Matafou** [comment]
I thought python for example had several version installed almost
everywhere because of heavy incompatibilites.

I do not consider as a minor point the fact that people seeking stability
do have stability.

Anyway stable-vx.x is what we want for them.

P.


2015-11-03 0:17 GMT+01:00 Guillaume Claret <notifications@github.com>:

**Comment by clarus** [comment]
> I thought python for example had several version installed almost everywhere because of heavy incompatibilites.

What do you mean by that?

> I do not consider as a minor point the fact that people seeking stability do have stability.

I agree with that.

> Anyway stable-vx.x is what we want for them.

It depends on what kind of stability we mean. When you do not upgrade, or when the dependencies are well stated, the `released` repository provides a stable installation.

**Comment by Matafou** [comment]
2015-11-03 1:04 GMT+01:00 Guillaume Claret <notifications@github.com>:

> I thought python for example had several version installed almost
> everywhere because of heavy incompatibilites.
>
> What do you mean by that?
>
On my debian, on a shell:
$ python<TAB>

python      python2.7   python3.3   python3.4   python3m    pythontex3
python2     python3     python3.3m  python3.4m  pythontex

I have 9 versions of python! Not one. Same for gcc:

$ gcc<TAB>
gcc             gcc-ar          gcc-nm-4.7      gcc-ranlib-4.8
gcc-4.6         gcc-ar-4.7      gcc-nm-4.8      gcc-ranlib-4.9
gcc-4.7         gcc-ar-4.8      gcc-nm-4.9      gcc-ranlib-5
gcc-4.8         gcc-ar-4.9      gcc-nm-5
gcc-4.9         gcc-ar-5        gcc-ranlib
gcc-5           gcc-nm          gcc-ranlib-4.7

As you say, programming language cannot be dealt with as other packages, we
often need to have several versions installed (if only to port code from a
version to another). But for now I would just ask for not removing a stable
version by a beta one. Then using stable-vX.X we should be able to give a
simple procedure to have several versions of coq coexisting.


> Anyway stable-vx.x is what we want for them.
>
> It depends on what kind of stability we mean. When you do not upgrade, or
> when the dependencies are well stated, the released repository provides a
> stable installation.
>
>
Stability means that MY developments (not only the libraries installed by
opam) that used to compile yesterday still compile today after a simple
upgrade. But I *want* to upgrade anyway from, say, 8.4pl6 to 8.4pl7 because
these are bugfixes only. But I don't want to upgrade to 8.5 without asking
for it explicitely. And of course I want a simple way to have both
installed on my system.

**Comment by clarus** [comment]
> But for now I would just ask for not removing a stable version by a beta one.

I agree that this was surely a mistake to add the beta. Too much enthusiasms from us.

> Then using stable-vX.X we should be able to give a simple procedure to have several versions of coq coexisting.

I think that the ability to have several Coq versions installed is independent of the architecture of repositories. In both the `released` or the `stable-vX.X` cases, we must use either switches or the `--root=` option to install several Coq. These are mechanisms which are provided by OPAM.

> Stability means that MY developments (not only the libraries installed by opam) that used to compile yesterday still compile today after a simple upgrade. But I *want* to upgrade anyway from, say, 8.4pl6 to 8.4pl7 because these are bugfixes only. But I don't want to upgrade to 8.5 without asking for it explicitely.

I think that, in general, the notion of "bugfixe only" upgrade is hard to define. And we have to define it not only for Coq, but also for all the libraries on which a development may depend. Thus, to me, in order to have a personal development which "still compiles", we must upgrade carefully or have an `opam` file describing the dependencies (as explained in [pinning](https://opam.ocaml.org/blog/opam-1-2-pin/)). Alternatively, we can refer to a particular stable distribution, but I think it is hard in practice to make frequent, complete and up-to-date distributions.

**Comment by clarus** [comment]
There is an unknown about whether a beta package should go to `released` (as it is a release) or `extra-dev` / `core-dev` (as it is a development version). This choice does not impact the `stable-*` repositories.

Do we agree that we should put the betas in `extra-dev` / `core-dev`? Having the betas in `released` seems to cause more harm than good.

**Comment by clarus** [comment]
Since this question may be ambiguous, I am talking about the betas of Coq and CoqIDE.

**Comment by clarus** [comment]
Solved by [Pull request 21](https://github.com/coq/opam-coq-archive/pull/21).
