### ISSUE TITLE
Redundant metadata

### ISSUE THREAD

**Issue by maximedenes** [coq/opam-coq-archive#787]
We currently have a lot of metadata that is duplicated for each version of a package. For example, authors, description, synospis, could all be attached to a package rather than each version, couldn't they?

In particular, which version of each package does the Coq Package Index website pick, in order to display the metadata? @gares

Context: I'm trying to consolidate the package metadata by extracting OPAM data to JSON.

**Comment by palmskog** [comment]
My observation is that authors, synopsis, and description all tend to evolve over time (albeit not in radical ways). You could use the rule that you always display the metadata for the latest version of a package. But for a fully accurate picture of the archive I think we should live with duplication rather than risk inaccuracy.

**Comment by maximedenes** [comment]
Do you mean that we want to map each version to a given list of authors and a description? Sounds like overkill to me. At least, the default should certainly not be to duplicate everything.

**Comment by palmskog** [comment]
I think we should, yes, at least at the level of raw JSON data (display could use a different approach). There is a lot of research that tries to investigate how authorship in software changes over time, and this data could be useful there.

**Comment by maximedenes** [comment]
> I think we should, yes, at least at the level of raw JSON data

I'm really not convinced, this is going to be useless for 90% of the packages. Normalizing data seems more important.

> There is a lot of research that tries to investigate how authorship in software changes over time, and this data could be useful there.

If that's the motivation, it can easily be extracted from the history of the repo instead.

**Comment by palmskog** [comment]
I don't call the shots around here, but I can say for sure that we would use the full JSON, and the "non-redundant" JSON would be far less useful. The interface for the OCaml OPAM archive seems to include everything for all versions, e.g., https://opam.ocaml.org/packages/afl-persistent/afl-persistent.1.2/

**Comment by maximedenes** [comment]
> I can say for sure that we would use the full JSON

Can you clarify what use case you have in mind?

> and the "non-redundant" JSON would be far less useful

I fail to see how redundancy can be useful. I guess you mean that we may need a way to override some fields per-version.

Understanding for each field what the good default is (factorizing vs being specific for each version) is a matter of inspecting the current metadata, I guess.

**Comment by gares** [comment]
My impression is that the metadata for the opam archive is not the authoritative one wrt authors, license & co (I actually don't get why they did put this piece of info there in the first place). My point is that nobody checks that the data part of an opam file actually matches the one declared in the upstream repository. For example in Debian or Ubuntu whenever a new package is added to the archive there is a dedicated team, the FTP team, that checks that indeed the license of the sources matches the one declared by the package (and that the license lets one redistribute the software) and whenever there is a new release the maintainer of the package has to check for license/copyright change (Debian is about free software, so this data is very relevant to its community). People involved in these processes went trough an exam, so they are supposed to know what a license it, etc...

I perfectly understand that having metadata such as authorship, license, etc in a single place and in a machine readable format could be a nice resource for some kind of research on the Coq ecosystem. But unfortunately I think that the opam archive, in spite of having a place this metadata, does not provide an authoritative or even correct source. And I also think ensuring this source is good goes behind the scope/manpower we have.

What could make sense, IMO, would be to "standardize" a format for this kind of metadata for Coq project, ask people to put in their sources such piece of info in that format (in that way their authoritative VCS could be queried also for authorship changes, for example, other than source code changes).
Authorship and license has nothing to do with opam or nix, and there already exist formats about that (Debian has one for example). Having the Coq packages page display this metadata would also be good, but having it part of the archive itself seems doomed to have/display wrong metadata. Again the original syn is in the opam format that has a field for that (other package managers do the same mistake, btw), and I should blame them for this I guess, but given we are discussing it here, ... here my thoughts.

**Comment by Zimmi48** [comment]
Opam and Nix have this metadata for the same reason that Debian has it. Package repositories contain package metadata, and this is part of the important metadata that one wants to have access to, and in particular one wants to be displayed on a package index. I agree that we don't have the manpower to check this info is correct as is done in Debian, but given that package authors or people close to the projects are most often the ones creating or updating the opam package, we can trust that in most cases this information will be correct.

nixpkgs also does not go as far as Debian: e.g. it has a license field, and review instructions say the reviewer should verify that the license has not changed when a package is updated. In practice, I doubt that this is actually done most of the time.

**Comment by gares** [comment]
> we can trust that in most cases this information will be correct.

+



> In practice, I doubt that this is actually done most of the time.

\bottom

;-)

**Comment by gares** [comment]
More seriously, where do you stand?

**Comment by Zimmi48** [comment]
I don't know where to stand because I don't know what is being proposed. Is it to reduce the amount of duplication in the repository? In this case, I don't know if it is possible with the current opam infrastructure. So, unless we choose to move to a packaging format that is independent of opam and consider that the opam and Nix repositories are generated from there (and we should seriously think before taking such a decision), then we are forced to stay compatible with what opam makes possible.

**Comment by palmskog** [comment]
My reading is that the proposal is that the Coq OPAM archive metadata exposed via JSON should include only a fraction of the "real" metadata, and should omit, e.g., authors per package version. This would be an inconvenience for us and may even force us to set up duplicate processing of `opam` files to get the complete metadata.

**Comment by Zimmi48** [comment]
@palmskog It seems that your speech has moved from talking about hypothetical use cases by hypothetical researchers to actual use case by yourself and your collaborators. It is an important distinction because it is not the same thing trying to accommodate hypothetical use cases and actual ones.

But independently of this, I am not sure that it makes sense to try to remove redundancy in the processing step, unless it is for compressing reasons, in which case, the intermediate representation should still be exhaustive by, e.g. having a way of specifying values that changed overtime.

I feel like waving hands in the air while the goals and stakes of this project, and the design that is sketched, have not been clearly specified.

**Comment by maximedenes** [comment]
Ok, I'll keep per-version data.
