### ISSUE TITLE
Sandboxing errors

### ISSUE THREAD

**Issue by maximedenes** [coq/opam-coq-archive#799]
CI jobs seem to fail on pyrolyse because of bubblewrap errors. See for example: https://gitlab.com/coq/opam-coq-archive/-/jobs/234147260

**Comment by clarus** [comment]
This may be due to the commit https://github.com/coq/opam-coq-archive/commit/10ee7ed364ab92efac287b3ab94fb98e83b12701 which added Bubblewrap one month ago. Surprisingly we have not had a bug since then, maybe we got lucky with the cache on the opam folder.

To me the simplest solution is to revert this commit. This will make the CI on new packages less realistic because most users have Bubblewrap. A typical package error with Bubblewrap: attempting to install files during the `build` phase.

**Comment by clarus** [comment]
@maximedenes I think we can close this issue, right? There were no bubblewrap errors for a long time on pull-requests.
